version: "3"
services:
  nginx:
    image: gihyodocker/nginx-proxy:latest
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role != manager
    environment:
      SERVICE_PORTS: 80
      BACKEND_HOST: echo_api:5000
    depends_on:
      - api
    networks:
      - echo

  api:
    image: registry:5000/example/echo:latest
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role != manager
    networks:
      - echo

networks:
  echo:
    external: true